use master
GO

DROP DATABASE IF EXISTS TestDB
GO

create database TestDB
GO

use TestDB
GO


-- In general joins work faster than sub-queries, but in reality it all depends 
-- on the execution plan that is generated by SQL Server.